service: lamda-by-serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: staging
  endpointType: REGIONAL

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
          cors: true
      - http:
          path: welcome
          method: GET
          cors: true

  hello2:
      handler: handler.hello2
      events:
        - http:
            path: hello2
            method: GET
            cors: true
      - http:
          path: welcome2
          method: GET
          cors: true